### ISSUE TITLE
Syntax Error: Unexpected token .

### ISSUE THREAD

**Issue by H4zze** [atlassian/gajira-login#40]
When I try to run this in a workflow I receive a syntax error. Please note that I'm only able to read the error using [Act](https://github.com/nektos/act).

Error
```
/run/act/actions/atlassian-gajira-login@master/dist/index.js:21407
    if (tag?.format)
            ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

Job
```
jobs:
  update-jira:
    name: Update JIRA ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
```
